version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./be
      # Only will build development stage from our dockerfile
      target: development
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:nnginx.conf:ro
