version: "3.8"
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - ./api/.env
    ports:
      - 3000:3000

  web:
    container_name: web
    build:
      context: ./web
      target: runner
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    env_file:
      - ./web/.env

  db:
    container_name: db
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file:
      - ./db/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  nginx:
    container_name: reverse_proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/certs:/etc/nginx/certs

volumes:
  pg_data:
