version: "3.8"
services:
  api:
    container_name: api
    image: minkoy1903/netflop_api:latest
    env_file:
      - ./api/.env
    ports:
      - 3000:3000

  web:
    image: minkoy1903/netflop_web:latest
    container_name: web
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    env_file:
      - ./web/.env

  db:
    container_name: db
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    env_file:
      - ./db/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql.conf

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/quyvo:/letsencrypt
      - /home/quyvo/certs:/etc/letsencrypt

volumes:
  pg_data:
