version: "3.8"
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./be
      # Only will build development stage from our dockerfile
      # target: development
    env_file:
      - ./be/.env
    command: npm run start:dev
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
