version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - ./api/.env
    ports:
      - 3000:3000

  web:
    container_name: web
    build:
      context: ./web
      target: runner
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    env_file:
      - ./web/.env

  nginx:
    container_name: reverse_proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/certs:/etc/nginx/certs
